// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package minmaxroutingpbf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Weight struct {
	Max                  []int32  `protobuf:"varint,1,rep,packed,name=Max,proto3" json:"Max,omitempty"`
	Min                  []int32  `protobuf:"varint,2,rep,packed,name=Min,proto3" json:"Min,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weight) Reset()         { *m = Weight{} }
func (m *Weight) String() string { return proto.CompactTextString(m) }
func (*Weight) ProtoMessage()    {}
func (*Weight) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Weight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weight.Unmarshal(m, b)
}
func (m *Weight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weight.Marshal(b, m, deterministic)
}
func (m *Weight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weight.Merge(m, src)
}
func (m *Weight) XXX_Size() int {
	return xxx_messageInfo_Weight.Size(m)
}
func (m *Weight) XXX_DiscardUnknown() {
	xxx_messageInfo_Weight.DiscardUnknown(m)
}

var xxx_messageInfo_Weight proto.InternalMessageInfo

func (m *Weight) GetMax() []int32 {
	if m != nil {
		return m.Max
	}
	return nil
}

func (m *Weight) GetMin() []int32 {
	if m != nil {
		return m.Min
	}
	return nil
}

type Leaf struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	BeforeNodeId         int32    `protobuf:"varint,3,opt,name=BeforeNodeId,proto3" json:"BeforeNodeId,omitempty"`
	BeforeIndex          int32    `protobuf:"varint,4,opt,name=BeforeIndex,proto3" json:"BeforeIndex,omitempty"`
	BeforeEdgeId         int32    `protobuf:"varint,5,opt,name=BeforeEdgeId,proto3" json:"BeforeEdgeId,omitempty"`
	Weight               *Weight  `protobuf:"bytes,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	IsUse                bool     `protobuf:"varint,7,opt,name=IsUse,proto3" json:"IsUse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leaf) Reset()         { *m = Leaf{} }
func (m *Leaf) String() string { return proto.CompactTextString(m) }
func (*Leaf) ProtoMessage()    {}
func (*Leaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *Leaf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leaf.Unmarshal(m, b)
}
func (m *Leaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leaf.Marshal(b, m, deterministic)
}
func (m *Leaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leaf.Merge(m, src)
}
func (m *Leaf) XXX_Size() int {
	return xxx_messageInfo_Leaf.Size(m)
}
func (m *Leaf) XXX_DiscardUnknown() {
	xxx_messageInfo_Leaf.DiscardUnknown(m)
}

var xxx_messageInfo_Leaf proto.InternalMessageInfo

func (m *Leaf) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *Leaf) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Leaf) GetBeforeNodeId() int32 {
	if m != nil {
		return m.BeforeNodeId
	}
	return 0
}

func (m *Leaf) GetBeforeIndex() int32 {
	if m != nil {
		return m.BeforeIndex
	}
	return 0
}

func (m *Leaf) GetBeforeEdgeId() int32 {
	if m != nil {
		return m.BeforeEdgeId
	}
	return 0
}

func (m *Leaf) GetWeight() *Weight {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (m *Leaf) GetIsUse() bool {
	if m != nil {
		return m.IsUse
	}
	return false
}

type RouteTree struct {
	Leaves               []*Leaf  `protobuf:"bytes,1,rep,name=Leaves,proto3" json:"Leaves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteTree) Reset()         { *m = RouteTree{} }
func (m *RouteTree) String() string { return proto.CompactTextString(m) }
func (*RouteTree) ProtoMessage()    {}
func (*RouteTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *RouteTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteTree.Unmarshal(m, b)
}
func (m *RouteTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteTree.Marshal(b, m, deterministic)
}
func (m *RouteTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteTree.Merge(m, src)
}
func (m *RouteTree) XXX_Size() int {
	return xxx_messageInfo_RouteTree.Size(m)
}
func (m *RouteTree) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteTree.DiscardUnknown(m)
}

var xxx_messageInfo_RouteTree proto.InternalMessageInfo

func (m *RouteTree) GetLeaves() []*Leaf {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func init() {
	proto.RegisterType((*Weight)(nil), "minmaxroutingpbf.Weight")
	proto.RegisterType((*Leaf)(nil), "minmaxroutingpbf.Leaf")
	proto.RegisterType((*RouteTree)(nil), "minmaxroutingpbf.RouteTree")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe5, 0xa6, 0x31, 0xe5, 0xc2, 0x50, 0x9d, 0x50, 0xe5, 0xd1, 0xca, 0x94, 0x01, 0x45,
	0xa8, 0x8c, 0x6c, 0x48, 0x0c, 0x95, 0x0a, 0x83, 0x05, 0x62, 0x4e, 0x94, 0x4b, 0xf0, 0x50, 0x3b,
	0x4a, 0x52, 0x94, 0x4f, 0xcc, 0xe7, 0x40, 0xfe, 0x53, 0x51, 0xe8, 0xe6, 0xf7, 0xbb, 0xbb, 0x27,
	0xbf, 0x07, 0xab, 0xbe, 0x2e, 0xfb, 0xc1, 0x4e, 0x16, 0xd7, 0x07, 0x6d, 0x0e, 0xd5, 0x3c, 0xd8,
	0xe3, 0xa4, 0x4d, 0xd7, 0xd7, 0x6d, 0x7e, 0x07, 0xfc, 0x83, 0x74, 0xf7, 0x39, 0xe1, 0x1a, 0x92,
	0x97, 0x6a, 0x16, 0x4c, 0x26, 0x45, 0xaa, 0xdc, 0xd3, 0x13, 0x6d, 0xc4, 0x22, 0x12, 0x6d, 0xf2,
	0x6f, 0x06, 0xcb, 0x3d, 0x55, 0x2d, 0x6e, 0x80, 0xbf, 0xda, 0x86, 0x76, 0x8d, 0x60, 0x92, 0x15,
	0xa9, 0x8a, 0x0a, 0x6f, 0x21, 0xdd, 0x99, 0x86, 0x66, 0xb1, 0xf0, 0x38, 0x08, 0xcc, 0xe1, 0xe6,
	0x89, 0x5a, 0x3b, 0x50, 0xbc, 0x49, 0xfc, 0xf0, 0x0f, 0x43, 0x09, 0x59, 0xd0, 0xe1, 0x7e, 0xe9,
	0x57, 0xce, 0xd1, 0xaf, 0xcb, 0x73, 0xd3, 0x39, 0x97, 0xf4, 0xdc, 0x25, 0x30, 0xbc, 0x3f, 0xc5,
	0x11, 0x5c, 0xb2, 0x22, 0xdb, 0x8a, 0xf2, 0x7f, 0xe2, 0x32, 0xcc, 0xd5, 0x29, 0xb6, 0xfb, 0xf1,
	0xf8, 0x3e, 0x92, 0xb8, 0x92, 0xac, 0x58, 0xa9, 0x20, 0xf2, 0x47, 0xb8, 0x56, 0xf6, 0x38, 0xd1,
	0xdb, 0x40, 0x84, 0x25, 0xf0, 0x3d, 0x55, 0x5f, 0x34, 0xfa, 0x72, 0xb2, 0xed, 0xe6, 0xd2, 0xd4,
	0x95, 0xa2, 0xe2, 0x56, 0xcd, 0x7d, 0xd9, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x75,
	0x46, 0x2a, 0x78, 0x01, 0x00, 0x00,
}
